<?php
/**
 * Copyright ©
 */

// @codingStandardsIgnoreFile

/** @var \Alpaca-Test\Checkout\Block\Cart\Customer\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="title"><h3><?= $block->escapeHtml(__('Customer Information')) ?></h3></div>
    <div class="block-content">
        <div class="box box-information">
            <div class="box-content">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Full Name')) ?></span>
                </strong>
                <div class="box-content">
                    <span>
                        <?= $block->escapeHtml($block->getName()) ?>
                    </span>
                </div>
            </div>
        </div>
        <div class="box box-information">
            <div class="box-content">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Email')) ?></span>
                </strong>
                <div class="box-content">
                    <span>
                        <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
