<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Alexvergara\BankDeposit\Block\Form\Bankdeposit
 */
$instructions = $block->getInstructions();
?>
<?php if ($instructions): ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display:none;">
        <li>
            <div class="<?= /* @noEscape */ $methodCode ?>-instructions-content checkout-agreement-item-content">
                <?= /* @noEscape */ nl2br($block->escapeHtml($instructions)) ?>
            </div>
        </li>
    </ul>
<?php endif;

$steps = $block->getSteps();
?>
<?php if ($steps): ?>
    <?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
    <ul class="form-list checkout-agreements" id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display:none;">
        <li>
            <div class="<?= /* @noEscape */ $methodCode ?>-instructions-content checkout-agreement-item-content">
                <?= /* @noEscape */ nl2br($block->escapeHtml($steps)) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>
